on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, reopened, synchronize]
  workflow_dispatch: # Manually invoked by user.

name: ci-master

env:
  NODE_VERSION: 20

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/build
        with:
          node-version: ${{ env.NODE_VERSION }}
          artifact-name: frontend

  containerize:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github

      - uses: ./.github/actions/containerize
        with:
          registry: ghcr.io
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          artifact-name: frontend
          push-image: ${{ github.ref_type == 'branch' && github.ref_protected && github.event_name != 'pull_request' }}

  trigger-deployment:
    runs-on: ubuntu-latest
    needs: containerize
    if: ${{ github.ref_type == 'branch' && github.ref_protected && github.event_name != 'pull_request' }}
    environment: production

    steps:
      - name: Call deployment webhook
        shell: bash
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          curl -X POST -d "" "$WEBHOOK_URL"
